export const productData = [
  // Mixed Products
  { name: 'Compact Side Table', category: 'Table', image: '/images/products/table/table1.png' },
  { name: 'Modern Wooden Chair', category: 'Chair', image: '/images/products/chair/chair1.png' },
  { name: 'Vintage Table Lamp', category: 'Lamp', image: '/images/products/lamp/lamp1.png' },
  { name: 'Red Velvet Dream Cake', category: 'Cake', image: '/images/products/cake/cake1.png' },
  { name: 'Tulip Spring Blooms', category: 'Flower', image: '/images/products/flower/flower1.png' },
  { name: 'Industrial Work Table', category: 'Table', image: '/images/products/table/table1.png' },
  { name: 'Modern Desk Lamp', category: 'Lamp', image: '/images/products/lamp/lamp2.png' },
  { name: 'Luxury Lounge Chair', category: 'Chair', image: '/images/products/chair/chair1.png' },
  { name: 'Chocolate Delight Cake', category: 'Cake', image: '/images/products/cake/cake1.png' },
  { name: 'Daisy Delight Bunch', category: 'Flower', image: '/images/products/flower/flower1.png' },
  { name: 'Classic Bedside Lamp', category: 'Lamp', image: '/images/products/lamp/lamp2.png' },
  { name: 'Classic Office Chair', category: 'Chair', image: '/images/products/chair/chair1.png' },
  { name: 'Rustic Wooden Table', category: 'Table', image: '/images/products/table/table1.png' },
  { name: 'Vanilla Celebration Cake', category: 'Cake', image: '/images/products/cake/cake1.png' },
  { name: 'Elegant Rose Bouquet', category: 'Flower', image: '/images/products/flower/flower1.png' },
  { name: 'Ergonomic Desk Chair', category: 'Chair', image: '/images/products/chair/chair1.png' },
  { name: 'Industrial Floor Lamp', category: 'Lamp', image: '/images/products/lamp/lamp1.png' },
  { name: 'Fruit Topped Delight Cake', category: 'Cake', image: '/images/products/cake/cake1.png' },
  { name: 'Minimalist Dining Chair', category: 'Chair', image: '/images/products/chair/chair1.png' },
  { name: 'Glass Coffee Table', category: 'Table', image: '/images/products/table/table2.png' },
  { name: 'Classic Cheesecake', category: 'Cake', image: '/images/products/cake/cake1.png' },
  { name: 'Sunflower Sunshine', category: 'Flower', image: '/images/products/flower/flower1.png' },
  { name: 'Modern Dining Table', category: 'Table', image: '/images/products/table/table3.png' },
  { name: 'Orchid Beauty Arrangement', category: 'Flower', image: '/images/products/flower/flower1.png' },
  { name: 'Contemporary Hanging Lamp', category: 'Lamp', image: '/images/products/lamp/lamp1.png' },
];
export const categories = {
  Chair: [1, 7, 11, 13, 15],
  Cake: [3, 9, 13, 17, 19],
  Flower: [4, 10, 14, 16, 18],
  Lamp: [2, 6, 10, 14, 20],
  Table: [0, 5, 12, 20, 23],
};
