import { Geist, Geist_Mono,Sail,Lexend_Deca} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./sections/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Crystal Decor",
  description: "Generated by create next app",
};

const sail = Sail({
  variable: "--font-sail",
  subsets: ["latin"],
  weight:["400"]
});
const lexendDeca = Lexend_Deca({
  variable: "--font-Lexend-Deca",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sail.variable} ${lexendDeca.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
